services:
  - title: "Осуществление функции Генпроектировщика: "
    description: "Аттестат соответствия №0002559-ГП на выполнение функций
      генпроектировщика на объектах третьего-четвертого класса сложности "
    image_url: https://lh3.googleusercontent.com/aida-public/AB6AXuAOa1DI9NL-zNZ7t9xrQgXYgBarw3o2S0o_gKJD_kV4pnEsFEesOC9O9meH5JhS9yIZOM_3QI2DR4WAKEPAOBhWK9f_QSToUaVWgHnMo-RO4Bj1TujOO8r7vS20MnhPPLH0mu6DSAh7hsdDyJyTHNAqUjAAw0IpEMqCkfCM7yF_QIZP68Yh1lJnYyBWG_T_0byXgfzrhqMFesJS8-ZBwMhaLLg-6hidJTQENibJH1mcFCuyvnzpwcseaz9kM08dUagJQzZrgOXoRffU
  - title: Проектирование разделов проектной документации для объектов строительства
      1-4 класса сложности
    description: >
      3.1. Генеральный план.

      3.2. Сметная документация.

      3.4. Конструктивные решения.

      3.6. Инженерное оборудование, внутренние сети и системы:
         3.6.1. электроснабжение, силовое электрооборудование и электроосвещение;
          3.6.2. связь и сигнализация, видеонаблюдение.
      3.8. Охрана окружающей среды. 

      3.9. Инженерно-технические мероприятия гражданской обороны. Мероприятия по предупреждению и ликвидации ЧС.

      Аттестат соответствия №0005213-ПР на разработку разделов проектной документации для объектов строительства 1-4 класса сложности.
    image_url: https://lh3.googleusercontent.com/aida-public/AB6AXuAt4zt69pqKkuC-LcZdA3T36-ElXuaFI1O-SFr0DbAjLq8q499MB1JvLSsGyKvsUjwdP9YRRkdm2MMXj0PF08RinE4lcbaTLU31n884UOfu_lqAgZD5MV3uY8FTwZCT46f7u-MjJk_ZPIJTmj-ORRvlYjHFDP0v9CNRdj2RhUrG883oyH8HY1oUCQLjNLuAkrmqO98dY9P9abOp4aOOMUJktgU9PlSwcO9o3iupHQh2y9Bg_4mW2tquNu3BRmxw3Zv1cbbWOBauyz98
  - title: Инженерное оборудование, наружные и внутренние сети связи
    description: >
      В рамках проектирования инженерного оборудования, наружных и внутренних
      сетей связи, разрабатываем разделы:

      - пожарная сигнализация;

      - оповещение и управление эвакуацией людей при пожаре;

      - автоматические установки пожаротушения;

      - системы контроля и управления доступом (СКУД);

      - видеонаблюдение;

      - локально-вычислительные сети и т.п.
    image_url: https://lh3.googleusercontent.com/aida-public/AB6AXuDIG_KLrGdZuGI1M83GRuUv1Oe_sxRjYUmVr6PpFWFviR1c6mNCQk4l8oLo4R9pGO_jC99xDVSkEofrmeZR__quKt2ZQDCz9RSJt_8Vjh-CNOyszbHnr_Y-J523KKlHspMXYdNWATmjhqu4datAbSPGt7EfmdyJejnUzIoCaV75Svo5wcRWh-gLW-IiELbr1feHA6NjgnmDKBNtiJQ74BLxSCTj8gi9u0NbRTbeO-WLVYHkJepvvcOHtwIiYzfaKQsQHahmoAANHdxr
  - title: Экспертная деятельность по обесепечению пожарной безопасности
    description: >-
      В рамках выполнения работ по Экспертной деятельности в области пожарной
      безопасности выполняем:

      - расчеты категорий помещений и зданий по взрывопожарной и пожарной опасности;

      - расчеты временных параметров эвакуации людей;

      - расчеты температурного режима пожара и среднеобъемной температуры на поверхности строительных конструкций; 

      - расчеты параметров легкосбрасываемых конструкций;

      - расчеты интенсивности теплового излучения при возможных пожарах (определение величины противопожарных разрывов).

      Лицензия МЧС на право осуществления деятельности по обеспечению пожарной безопасности №31130/3339
    image_url: https://lh3.googleusercontent.com/aida-public/AB6AXuD-3C4ZRT4IaGC2Ghuj3cFcUaFiNpUVpUZJN7JPt8gMMIvNkKF1b4lIEZyRkMFElKcla1G1PDeTH164TQ959I4IIgtBHO0ggH73yuuJ2re7rPl2PVd7OEaWVHgPH0QdQHbzjqUgOkP87aKd-kESMi99qMjhiQwdGmuh5t7B_zTOWH9Gc5jSIjsd6zVZInY8Ae_EVwJhqZfFRtne2888ZZ1qQBdJr5VQh4-5casQaIAzxNOtxHhMWEeDjrUyJZMd92OQopjs4i30mhAD
